import { DeriveParams } from './types'

/**
 * A sample Derive payload for a database with a table of User (id: int, name: string, email: string)
 *
 *  type Mutation {
 *     # Derived mutation
 *     CustomInsertUser(email: String!, name: String!): CustomInsertUserOutput
 *   }
 *
 *   type Mutation {
 *     InsertUserAction(user_info: UserInfo!): TokenOutput
 *   }
 *
 *   input UserInfo {
 *     username: String!
 *     password: String!
 *   }
 *
 *   type TokenOutput {
 *     accessToken: String!
 *   }
 *
 *   type CustomInsertUserOutput {
 *     email: String!
 *     id: Int!
 *     name: String!
 *   }
 *
 */
export const customInsertUserDerive: DeriveParams = {
  introspection_schema: {
    __schema: {
      directives: [
        {
          args: [
            {
              defaultValue: null,
              description: null,
              name: 'if',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Boolean', ofType: null },
              },
            },
          ],
          description: null,
          locations: ['FIELD', 'FRAGMENT_SPREAD', 'INLINE_FRAGMENT'],
          name: 'include',
        },
        {
          args: [
            {
              defaultValue: null,
              description: null,
              name: 'if',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Boolean', ofType: null },
              },
            },
          ],
          description: null,
          locations: ['FIELD', 'FRAGMENT_SPREAD', 'INLINE_FRAGMENT'],
          name: 'skip',
        },
      ],
      mutationType: { name: 'mutation_root' },
      queryType: { name: 'query_root' },
      subscriptionType: { name: 'subscription_root' },
      types: [
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'Boolean',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'email',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'CustomInsertUserOutput',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'Float',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'ID',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'Int',
          possibleTypes: null,
        },
        {
          description:
            "expression to compare columns of type Int. All fields are combined with logical 'AND'.",
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: '_eq',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gt',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gte',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_in',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_is_null',
              type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lt',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lte',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_neq',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nin',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'Int_comparison_exp',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'String',
          possibleTypes: null,
        },
        {
          description:
            "expression to compare columns of type String. All fields are combined with logical 'AND'.",
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: '_eq',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gt',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gte',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_ilike',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_in',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'String', ofType: null },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_is_null',
              type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_like',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lt',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lte',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_neq',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nilike',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nin',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'String', ofType: null },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nlike',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nsimilar',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_similar',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'String_comparison_exp',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'accessToken',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'TokenOutput',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'password',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'username',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'UserInfo',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'args',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'OBJECT',
                      name: '__InputValue',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'description',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'locations',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'ENUM',
                      name: '__DirectiveLocation',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__Directive',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: [
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'ARGUMENT_DEFINITION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'ENUM',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'ENUM_VALUE',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'FIELD',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'FIELD_DEFINITION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'FRAGMENT_DEFINITION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'FRAGMENT_SPREAD',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INLINE_FRAGMENT',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INPUT_FIELD_DEFINITION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INPUT_OBJECT',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INTERFACE',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'MUTATION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'OBJECT',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'QUERY',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'SCALAR',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'SCHEMA',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'SUBSCRIPTION',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'UNION',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: '__DirectiveLocation',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'deprecationReason',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'description',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'isDeprecated',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Boolean', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__EnumValue',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'args',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'OBJECT',
                      name: '__InputValue',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'deprecationReason',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'description',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'isDeprecated',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Boolean', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'type',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__Field',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'defaultValue',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'description',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'type',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__InputValue',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'directives',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'OBJECT',
                      name: '__Directive',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'mutationType',
              type: { kind: 'OBJECT', name: '__Type', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'queryType',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'subscriptionType',
              type: { kind: 'OBJECT', name: '__Type', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'types',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
                  },
                },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__Schema',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'description',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [
                {
                  defaultValue: 'false',
                  description: null,
                  name: 'includeDeprecated',
                  type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
                },
              ],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'enumValues',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: '__EnumValue', ofType: null },
                },
              },
            },
            {
              args: [
                {
                  defaultValue: 'false',
                  description: null,
                  name: 'includeDeprecated',
                  type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
                },
              ],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'fields',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: '__Field', ofType: null },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'inputFields',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: {
                    kind: 'OBJECT',
                    name: '__InputValue',
                    ofType: null,
                  },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'interfaces',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
                },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'kind',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'ENUM', name: '__TypeKind', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'ofType',
              type: { kind: 'OBJECT', name: '__Type', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'possibleTypes',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'OBJECT', name: '__Type', ofType: null },
                },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: '__Type',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: [
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'ENUM',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INPUT_OBJECT',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'INTERFACE',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'LIST',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'NON_NULL',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'OBJECT',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'SCALAR',
            },
            {
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'UNION',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: '__TypeKind',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'json',
          possibleTypes: null,
        },
        {
          description:
            "expression to compare columns of type json. All fields are combined with logical 'AND'.",
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: '_eq',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gt',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_gte',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_in',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'json', ofType: null },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_is_null',
              type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lt',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_lte',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_neq',
              type: { kind: 'SCALAR', name: 'json', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: '_nin',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'NON_NULL',
                  name: null,
                  ofType: { kind: 'SCALAR', name: 'json', ofType: null },
                },
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'json_comparison_exp',
          possibleTypes: null,
        },
        {
          description: 'mutation root',
          enumValues: null,
          fields: [
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'email',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'SCALAR', name: 'String', ofType: null },
                  },
                },
                {
                  defaultValue: null,
                  description: null,
                  name: 'name',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'SCALAR', name: 'String', ofType: null },
                  },
                },
              ],
              deprecationReason: null,
              description: 'perform the action: "CustomInsertUser"',
              isDeprecated: false,
              name: 'CustomInsertUser',
              type: {
                kind: 'OBJECT',
                name: 'CustomInsertUserOutput',
                ofType: null,
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'user_info',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'UserInfo',
                      ofType: null,
                    },
                  },
                },
              ],
              deprecationReason: null,
              description: 'perform the action: "InsertUserAction"',
              isDeprecated: false,
              name: 'InsertUserAction',
              type: { kind: 'OBJECT', name: 'TokenOutput', ofType: null },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: 'filter the rows which have to be deleted',
                  name: 'where',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_bool_exp',
                      ofType: null,
                    },
                  },
                },
              ],
              deprecationReason: null,
              description: 'delete data from the table: "user"',
              isDeprecated: false,
              name: 'delete_user',
              type: {
                kind: 'OBJECT',
                name: 'user_mutation_response',
                ofType: null,
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'id',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
                  },
                },
              ],
              deprecationReason: null,
              description: 'delete single row from the table: "user"',
              isDeprecated: false,
              name: 'delete_user_by_pk',
              type: { kind: 'OBJECT', name: 'user', ofType: null },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: 'the rows to be inserted',
                  name: 'objects',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'LIST',
                      name: null,
                      ofType: {
                        kind: 'NON_NULL',
                        name: null,
                        ofType: {
                          kind: 'INPUT_OBJECT',
                          name: 'user_insert_input',
                          ofType: null,
                        },
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'on conflict condition',
                  name: 'on_conflict',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_on_conflict',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'insert data into the table: "user"',
              isDeprecated: false,
              name: 'insert_user',
              type: {
                kind: 'OBJECT',
                name: 'user_mutation_response',
                ofType: null,
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: 'the row to be inserted',
                  name: 'object',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_insert_input',
                      ofType: null,
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'on conflict condition',
                  name: 'on_conflict',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_on_conflict',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'insert a single row into the table: "user"',
              isDeprecated: false,
              name: 'insert_user_one',
              type: { kind: 'OBJECT', name: 'user', ofType: null },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description:
                    'increments the integer columns with given value of the filtered values',
                  name: '_inc',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_inc_input',
                    ofType: null,
                  },
                },
                {
                  defaultValue: null,
                  description:
                    'sets the columns of the filtered rows to the given values',
                  name: '_set',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_set_input',
                    ofType: null,
                  },
                },
                {
                  defaultValue: null,
                  description: 'filter the rows which have to be updated',
                  name: 'where',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_bool_exp',
                      ofType: null,
                    },
                  },
                },
              ],
              deprecationReason: null,
              description: 'update data of the table: "user"',
              isDeprecated: false,
              name: 'update_user',
              type: {
                kind: 'OBJECT',
                name: 'user_mutation_response',
                ofType: null,
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description:
                    'increments the integer columns with given value of the filtered values',
                  name: '_inc',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_inc_input',
                    ofType: null,
                  },
                },
                {
                  defaultValue: null,
                  description:
                    'sets the columns of the filtered rows to the given values',
                  name: '_set',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_set_input',
                    ofType: null,
                  },
                },
                {
                  defaultValue: null,
                  description: null,
                  name: 'pk_columns',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_pk_columns_input',
                      ofType: null,
                    },
                  },
                },
              ],
              deprecationReason: null,
              description: 'update single row of the table: "user"',
              isDeprecated: false,
              name: 'update_user_by_pk',
              type: { kind: 'OBJECT', name: 'user', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'mutation_root',
          possibleTypes: null,
        },
        {
          description: 'column ordering options',
          enumValues: [
            {
              deprecationReason: null,
              description: 'in the ascending order, nulls last',
              isDeprecated: false,
              name: 'asc',
            },
            {
              deprecationReason: null,
              description: 'in the ascending order, nulls first',
              isDeprecated: false,
              name: 'asc_nulls_first',
            },
            {
              deprecationReason: null,
              description: 'in the ascending order, nulls last',
              isDeprecated: false,
              name: 'asc_nulls_last',
            },
            {
              deprecationReason: null,
              description: 'in the descending order, nulls first',
              isDeprecated: false,
              name: 'desc',
            },
            {
              deprecationReason: null,
              description: 'in the descending order, nulls first',
              isDeprecated: false,
              name: 'desc_nulls_first',
            },
            {
              deprecationReason: null,
              description: 'in the descending order, nulls last',
              isDeprecated: false,
              name: 'desc_nulls_last',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: 'order_by',
          possibleTypes: null,
        },
        {
          description: 'query root',
          enumValues: null,
          fields: [
            {
              args: [
                {
                  defaultValue: null,
                  description: 'distinct select on columns',
                  name: 'distinct_on',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'ENUM',
                        name: 'user_select_column',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'limit the number of rows returned',
                  name: 'limit',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'skip the first n rows. Use only with order_by',
                  name: 'offset',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'sort the rows by one or more columns',
                  name: 'order_by',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'INPUT_OBJECT',
                        name: 'user_order_by',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'filter the rows returned',
                  name: 'where',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_bool_exp',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'fetch data from the table: "user"',
              isDeprecated: false,
              name: 'user',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'OBJECT', name: 'user', ofType: null },
                  },
                },
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: 'distinct select on columns',
                  name: 'distinct_on',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'ENUM',
                        name: 'user_select_column',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'limit the number of rows returned',
                  name: 'limit',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'skip the first n rows. Use only with order_by',
                  name: 'offset',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'sort the rows by one or more columns',
                  name: 'order_by',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'INPUT_OBJECT',
                        name: 'user_order_by',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'filter the rows returned',
                  name: 'where',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_bool_exp',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'fetch aggregated fields from the table: "user"',
              isDeprecated: false,
              name: 'user_aggregate',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'user_aggregate',
                  ofType: null,
                },
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'id',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
                  },
                },
              ],
              deprecationReason: null,
              description:
                'fetch data from the table: "user" using primary key columns',
              isDeprecated: false,
              name: 'user_by_pk',
              type: { kind: 'OBJECT', name: 'user', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'query_root',
          possibleTypes: null,
        },
        {
          description: 'subscription root',
          enumValues: null,
          fields: [
            {
              args: [
                {
                  defaultValue: null,
                  description: 'distinct select on columns',
                  name: 'distinct_on',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'ENUM',
                        name: 'user_select_column',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'limit the number of rows returned',
                  name: 'limit',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'skip the first n rows. Use only with order_by',
                  name: 'offset',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'sort the rows by one or more columns',
                  name: 'order_by',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'INPUT_OBJECT',
                        name: 'user_order_by',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'filter the rows returned',
                  name: 'where',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_bool_exp',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'fetch data from the table: "user"',
              isDeprecated: false,
              name: 'user',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'OBJECT', name: 'user', ofType: null },
                  },
                },
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: 'distinct select on columns',
                  name: 'distinct_on',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'ENUM',
                        name: 'user_select_column',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'limit the number of rows returned',
                  name: 'limit',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'skip the first n rows. Use only with order_by',
                  name: 'offset',
                  type: { kind: 'SCALAR', name: 'Int', ofType: null },
                },
                {
                  defaultValue: null,
                  description: 'sort the rows by one or more columns',
                  name: 'order_by',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'INPUT_OBJECT',
                        name: 'user_order_by',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: 'filter the rows returned',
                  name: 'where',
                  type: {
                    kind: 'INPUT_OBJECT',
                    name: 'user_bool_exp',
                    ofType: null,
                  },
                },
              ],
              deprecationReason: null,
              description: 'fetch aggregated fields from the table: "user"',
              isDeprecated: false,
              name: 'user_aggregate',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'OBJECT',
                  name: 'user_aggregate',
                  ofType: null,
                },
              },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'id',
                  type: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
                  },
                },
              ],
              deprecationReason: null,
              description:
                'fetch data from the table: "user" using primary key columns',
              isDeprecated: false,
              name: 'user_by_pk',
              type: { kind: 'OBJECT', name: 'user', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'subscription_root',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'timestamptz',
          possibleTypes: null,
        },
        {
          description: 'columns and relationships of "user"',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'email',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'String', ofType: null },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user',
          possibleTypes: null,
        },
        {
          description: 'aggregated selection of "user"',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'aggregate',
              type: {
                kind: 'OBJECT',
                name: 'user_aggregate_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'nodes',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'OBJECT', name: 'user', ofType: null },
                  },
                },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_aggregate',
          possibleTypes: null,
        },
        {
          description: 'aggregate fields of "user"',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'avg',
              type: { kind: 'OBJECT', name: 'user_avg_fields', ofType: null },
            },
            {
              args: [
                {
                  defaultValue: null,
                  description: null,
                  name: 'columns',
                  type: {
                    kind: 'LIST',
                    name: null,
                    ofType: {
                      kind: 'NON_NULL',
                      name: null,
                      ofType: {
                        kind: 'ENUM',
                        name: 'user_select_column',
                        ofType: null,
                      },
                    },
                  },
                },
                {
                  defaultValue: null,
                  description: null,
                  name: 'distinct',
                  type: { kind: 'SCALAR', name: 'Boolean', ofType: null },
                },
              ],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'count',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'max',
              type: { kind: 'OBJECT', name: 'user_max_fields', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'min',
              type: { kind: 'OBJECT', name: 'user_min_fields', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'stddev',
              type: {
                kind: 'OBJECT',
                name: 'user_stddev_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'stddev_pop',
              type: {
                kind: 'OBJECT',
                name: 'user_stddev_pop_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'stddev_samp',
              type: {
                kind: 'OBJECT',
                name: 'user_stddev_samp_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'sum',
              type: { kind: 'OBJECT', name: 'user_sum_fields', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'var_pop',
              type: {
                kind: 'OBJECT',
                name: 'user_var_pop_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'var_samp',
              type: {
                kind: 'OBJECT',
                name: 'user_var_samp_fields',
                ofType: null,
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'variance',
              type: {
                kind: 'OBJECT',
                name: 'user_variance_fields',
                ofType: null,
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_aggregate_fields',
          possibleTypes: null,
        },
        {
          description: 'order by aggregate values of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'avg',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_avg_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'count',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'max',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_max_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'min',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_min_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'stddev',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_stddev_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'stddev_pop',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_stddev_pop_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'stddev_samp',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_stddev_samp_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'sum',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_sum_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'var_pop',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_var_pop_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'var_samp',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_var_samp_order_by',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'variance',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_variance_order_by',
                ofType: null,
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_aggregate_order_by',
          possibleTypes: null,
        },
        {
          description:
            'input type for inserting array relation for remote table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'data',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'INPUT_OBJECT',
                      name: 'user_insert_input',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'on_conflict',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_on_conflict',
                ofType: null,
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_arr_rel_insert_input',
          possibleTypes: null,
        },
        {
          description: 'aggregate avg on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_avg_fields',
          possibleTypes: null,
        },
        {
          description: 'order by avg() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_avg_order_by',
          possibleTypes: null,
        },
        {
          description:
            'Boolean expression to filter rows from the table "user". All fields are combined with a logical \'AND\'.',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: '_and',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_bool_exp',
                  ofType: null,
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_not',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_bool_exp',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: '_or',
              type: {
                kind: 'LIST',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_bool_exp',
                  ofType: null,
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'String_comparison_exp',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'Int_comparison_exp',
                ofType: null,
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'String_comparison_exp',
                ofType: null,
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_bool_exp',
          possibleTypes: null,
        },
        {
          description: 'unique or primary key constraints on table "user"',
          enumValues: [
            {
              deprecationReason: null,
              description: 'unique or primary key constraint',
              isDeprecated: false,
              name: 'user_pkey',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: 'user_constraint',
          possibleTypes: null,
        },
        {
          description:
            'input type for incrementing integer columne in table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_inc_input',
          possibleTypes: null,
        },
        {
          description: 'input type for inserting data into table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_insert_input',
          possibleTypes: null,
        },
        {
          description: 'aggregate max on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'email',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_max_fields',
          possibleTypes: null,
        },
        {
          description: 'order by max() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_max_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate min on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'email',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'name',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_min_fields',
          possibleTypes: null,
        },
        {
          description: 'order by min() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_min_order_by',
          possibleTypes: null,
        },
        {
          description: 'response of any mutation on the table "user"',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: 'number of affected rows by the mutation',
              isDeprecated: false,
              name: 'affected_rows',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
              },
            },
            {
              args: [],
              deprecationReason: null,
              description: 'data of the affected rows by the mutation',
              isDeprecated: false,
              name: 'returning',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: { kind: 'OBJECT', name: 'user', ofType: null },
                  },
                },
              },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_mutation_response',
          possibleTypes: null,
        },
        {
          description:
            'input type for inserting object relation for remote table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'data',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'INPUT_OBJECT',
                  name: 'user_insert_input',
                  ofType: null,
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'on_conflict',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_on_conflict',
                ofType: null,
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_obj_rel_insert_input',
          possibleTypes: null,
        },
        {
          description: 'on conflict condition type for table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'constraint',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'ENUM', name: 'user_constraint', ofType: null },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'update_columns',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: {
                  kind: 'LIST',
                  name: null,
                  ofType: {
                    kind: 'NON_NULL',
                    name: null,
                    ofType: {
                      kind: 'ENUM',
                      name: 'user_update_column',
                      ofType: null,
                    },
                  },
                },
              },
            },
            {
              defaultValue: null,
              description: null,
              name: 'where',
              type: {
                kind: 'INPUT_OBJECT',
                name: 'user_bool_exp',
                ofType: null,
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_on_conflict',
          possibleTypes: null,
        },
        {
          description: 'ordering options when selecting data from "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_order_by',
          possibleTypes: null,
        },
        {
          description: 'primary key columns input for table: "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: {
                kind: 'NON_NULL',
                name: null,
                ofType: { kind: 'SCALAR', name: 'Int', ofType: null },
              },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_pk_columns_input',
          possibleTypes: null,
        },
        {
          description: 'select columns of table "user"',
          enumValues: [
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'email',
            },
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'id',
            },
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'name',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: 'user_select_column',
          possibleTypes: null,
        },
        {
          description: 'input type for updating data in table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'email',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
            {
              defaultValue: null,
              description: null,
              name: 'name',
              type: { kind: 'SCALAR', name: 'String', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_set_input',
          possibleTypes: null,
        },
        {
          description: 'aggregate stddev on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_stddev_fields',
          possibleTypes: null,
        },
        {
          description: 'order by stddev() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_stddev_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate stddev_pop on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_stddev_pop_fields',
          possibleTypes: null,
        },
        {
          description: 'order by stddev_pop() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_stddev_pop_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate stddev_samp on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_stddev_samp_fields',
          possibleTypes: null,
        },
        {
          description: 'order by stddev_samp() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_stddev_samp_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate sum on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Int', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_sum_fields',
          possibleTypes: null,
        },
        {
          description: 'order by sum() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_sum_order_by',
          possibleTypes: null,
        },
        {
          description: 'update columns of table "user"',
          enumValues: [
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'email',
            },
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'id',
            },
            {
              deprecationReason: null,
              description: 'column name',
              isDeprecated: false,
              name: 'name',
            },
          ],
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'ENUM',
          name: 'user_update_column',
          possibleTypes: null,
        },
        {
          description: 'aggregate var_pop on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_var_pop_fields',
          possibleTypes: null,
        },
        {
          description: 'order by var_pop() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_var_pop_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate var_samp on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_var_samp_fields',
          possibleTypes: null,
        },
        {
          description: 'order by var_samp() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_var_samp_order_by',
          possibleTypes: null,
        },
        {
          description: 'aggregate variance on columns',
          enumValues: null,
          fields: [
            {
              args: [],
              deprecationReason: null,
              description: null,
              isDeprecated: false,
              name: 'id',
              type: { kind: 'SCALAR', name: 'Float', ofType: null },
            },
          ],
          inputFields: null,
          interfaces: [],
          kind: 'OBJECT',
          name: 'user_variance_fields',
          possibleTypes: null,
        },
        {
          description: 'order by variance() on columns of table "user"',
          enumValues: null,
          fields: null,
          inputFields: [
            {
              defaultValue: null,
              description: null,
              name: 'id',
              type: { kind: 'ENUM', name: 'order_by', ofType: null },
            },
          ],
          interfaces: null,
          kind: 'INPUT_OBJECT',
          name: 'user_variance_order_by',
          possibleTypes: null,
        },
        {
          description: null,
          enumValues: null,
          fields: null,
          inputFields: null,
          interfaces: null,
          kind: 'SCALAR',
          name: 'uuid',
          possibleTypes: null,
        },
      ],
    },
  },
  operation:
    'mutation CustomInsertUser($email: String!, $name: String!) {\n  insert_user_one(object: {email: $email, name: $name}) {\n      id\n      name\n      email\n  }\n}',
  action_name: '',
}
