export { typescriptExpressTemplate } from './typescriptExpress'
export { javascriptExpressTemplate } from './javascriptExpress'
export { goServeMuxTemplate } from './goServeMux'
export { kotlinHttp4kTemplate } from './http4kBasic'
export { kotlinKtorTemplate } from './kotlinKtor'
export { pythonFastAPITemplate } from './pythonFastAPI'
